name: "Next Release Changelog Generator"
description: "Create a changelog based on your release body."
inputs:
  changelog:
    description: 'Filepath to changelog'
    required: true
    default: 'CHANGELOG.md'
  token:
    required: true
    description: '<path to token>'
  use_pullrequest:
    default: false
    description: 'Use a pull request to generate the changelog instead of a direct commit'
  branch_name:
    required: false
    description: 'The branch name to use for a pull request for your changelog (If `use_pullrequest` is true)'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'list'
