on:
  release:
    types: [published]
jobs:
  testing_one:
    runs-on: ubuntu-latest
    name: Update Changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create Changelog.md
        id: changelog
        uses: donaldwasserman/test-action@master
        with:
          changelog: 'CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}
